### ISSUE TITLE
oscillator of null

### ISSUE THREAD

**Issue by ianmsfvenom** [ozdemirburak/morse-decoder#19]
```
const oscillator = offlineContext.createOscillator();
                                      ^

TypeError: Cannot read property 'createOscillator' of null
```
I can't resolve this error, something can help me?

**Comment by ozdemirburak** [comment]
Check the browser compatibility for `OfflineAudioContext` here:

https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext

**Comment by ianmsfvenom** [comment]
is nodejs compatible?

**Comment by ozdemirburak** [comment]
Unfortunately, as far as I know, Node.js doesn't support it.
