### ISSUE TITLE
Sending request HTTP request to https://morsedecoder.com/

### ISSUE THREAD

**Issue by ALiwoto** [ozdemirburak/morse-decoder#20]
Is it possible to send HTTP requests to https://morsedecoder.com/ with content and get the encoded value?
If it's not possible, is it possible to add it as a _new feature_ to the site?

**Comment by chris--jones** [comment]
@ALiwoto - Seems no one is going to answer this, but I reckon it's not applicable as you're referencing the related website and this project is specifically for the library

In my opinion it's also fairly pointless for @ozdemirburak to add such a feature or API given that it would just add load to his server and the library is freely available here.

I'd advise this issue be closed as "will not fix"

**Comment by ALiwoto** [comment]
@chris--jones you are actually right. Now that I look back at it, I do have your opinion as well.
Since this is just a library, and not an API. I will close the issue as not planned.
