### ISSUE TITLE
Migrate Code to TypeScript

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/morse-decoder#21]
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by drishit96** [comment]
Hi @ozdemirburak, I'd like to work on this

**Comment by ozdemirburak** [comment]
Sure, @drishit96.

**Comment by drishit96** [comment]
@ozdemirburak I have run the tests and they work but the jshint lint is not working since the js file generated by typescript is not jshint compatible. Should I replace jshint with eslint?

**Comment by ozdemirburak** [comment]
That'd be great @drishit96.
