### ISSUE TITLE
Split Typescript logic into several files 

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/morse-decoder#23]
Currently, there is only one typescript file, [index.ts](https://github.com/ozdemirburak/morse-decoder/blob/master/src/index.ts).

To split the logic, you can create files like:

- characters.ts
- audio.ts

**Comment by Pervolarakis** [comment]
can i work on this?

**Comment by chris--jones** [comment]
I feel like this is going to be a little opinionated, but I'm game to try :)

**Comment by ozdemirburak** [comment]
Sounds great, @chris--jones. Thanks.

**Comment by chris--jones** [comment]
I did the splitting, now I just need to figure out now how to recombine them
