### ISSUE TITLE
Hatalı tanımlama

### ISSUE THREAD

**Issue by Bulllut** [ozdemirburak/morse-decoder#26]
7 rakamının görsel açıklamasında hata var.
![Screenshot_2023-09-19-13-40-32-101_com whatsapp](https://github.com/ozdemirburak/morse-decoder/assets/145449532/310ccdad-13fd-4876-b60b-ab9ae0bbafbc)

**Comment by ozdemirburak** [comment]
Bende bu şekilde hala? <img width="797" alt="image" src="https://github.com/ozdemirburak/morse-decoder/assets/5355510/5774446e-13e9-483a-a55c-64f9d3b25124">

**Comment by ozdemirburak** [comment]
Bunu şimdilik kapatıyorum, çünkü hatayı tekrar üretemedim. Hatanın nasıl oluştuğunu detaylandırırsanız yine açabiliriz.
